name: create release

on:
  push:
    tags:
      - '*'

jobs:
  release_binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: linux
          - os: macos-latest
            suffix: macos
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: current tag
      id: current_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: package
      run: tar -czvf adbc-${{ matrix.suffix }}-${{ steps.current_tag.outputs.tag }}.tar.gz -C build adbc
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '*.tar.gz'
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
